version: "3.9"

services:
  postgresdb:
    image: postgres:latest
    restart: always
    container_name: "sculift_pg"
    environment:
      - POSTGRES_USER=shyamjith
      - POSTGRES_PASSWORD=funnyhow
      - POSTGRES_DB=lift
      - DATABASE_HOST=localhost
    ports:
      - "5299:5432"

  app:
    container_name: sculift_app
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - JWT-SECRET_KEY=${JWT-SECRET_KEY}
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - postgresdb

  redisdb:
    image: redis:latest
    container_name: "sculift_rdb"
    ports:
      - "4578:6379"
